# Generated by Django 3.0.6 on 2020-05-17 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cropName', models.CharField(max_length=30)),
                ('altitude', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('manpower', models.CharField(max_length=100)),
                ('fertilizer', models.CharField(max_length=100)),
                ('insecticides', models.CharField(max_length=50)),
                ('pesticides', models.CharField(max_length=50)),
                ('investment', models.CharField(max_length=50)),
                ('turnover', models.CharField(max_length=50)),
                ('breakeven', models.CharField(max_length=50)),
                ('places', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Crop',
                'verbose_name_plural': 'Crops',
            },
        ),
    ]
