# Generated by Django 3.0.6 on 2020-05-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crops',
            name='humidity',
            field=models.FloatField(),
        ),
    ]
