# Generated by Django 3.0.6 on 2020-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('krishiapp', '0002_auto_20200517_0408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crops',
            name='altitude',
        ),
        migrations.AddField(
            model_name='crops',
            name='maxAltitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crops',
            name='minAltitude',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
